services:
  model:
    build:
      context: ./models
      dockerfile: Dockerfile
    container_name: model_api
    volumes:
      - ./models:/app
    ports:
      - "8000:8000"
    networks:
      - templet



networks:
  templet:
    driver: bridge
